name: Michael Friedman Premier Mortgage Advisement
favicon: null
layout_spectrum: 0.56996
typography_spectrum: 0.93209
title: Michael Friedman Premier Mortgage Advisment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#656654'
    - '#a4a499'
    - '#e1e0da'
    - '#404040'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.6587577990721911
purpose: []
