name: Michael Friedman Premier Mortgage Advisement
favicon: null
layout_spectrum: 0.5613739457912743
typography_spectrum: 0.06908429064787924
title: Michael Friedman Premier Mortgage Advisment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3921054764650762
  lightness: 0.9557988692540675
  saturation: 0.35662032081745565
  rhythmicContrast: 0.6587577990721911
purpose: []
